name: Azure Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: carelink3
  AZURE_WEBAPP_NAME_FRONTEND: carelink3-frontend
  AZURE_WEBAPP_PACKAGE_PATH: './'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Dependencies (Backend)
        working-directory: ./backend
        run: npm install

      - name: Build (Backend)
        working-directory: ./backend
        run: npm run build
        env:
          CI: false

      - name: Install Dependencies (Frontend)
        working-directory: ./frontend
        run: npm install

      - name: Build (Frontend)
        working-directory: ./frontend
        run: npm run build
        env:
          CI: false

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend

      - name: 'Deploy Frontend to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_FRONTEND }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_FRONTEND_PUBLISH_PROFILE }}
          package: ./frontend/build 